language: cpp
env:
  global:
   #- DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      sudo: true
      #dist: "xenial"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode8.3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/833f2fca8ab17c49d455
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get install libboost-dev libssl-dev libxml2-dev bluez zlib1g-dev cmake-data
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
    fi
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew install boost
    fi
    pwd
    cd ..
    pwd
script:
  - |
    g++ -v
    cd ${TRAVIS_BUILD_DIR}
    cd ..
    git clone --depth=1 https://necktwi@github.com/necktwi/ferrybase.git
    cd ferrybase
    mkdir -p build
    cd build
    if [ $TRAVIS_OS_NAME = linux ]; then
      cmake ..
      make
    fi
    if [ $TRAVIS_OS_NAME = osx ]; then
      cmake .. -G Xcode
      xcodebuild
    fi
    pwd
    cd ${TRAVIS_BUILD_DIR}
    cd ..
    git clone --depth=1 https://necktwi@github.com/necktwi/logger.git
    cd logger
    mkdir -p build
    cd build
    if [ $TRAVIS_OS_NAME = linux ]; then
      cmake ..
      make
    fi
    if [ $TRAVIS_OS_NAME = osx ]; then
      cmake .. -G Xcode
      xcodebuild
    fi
    pwd
    cd ${TRAVIS_BUILD_DIR}
    mkdir -p build
    cd build
    if [ $TRAVIS_OS_NAME = linux ]; then
      cmake ..
      make
    fi
    if [ $TRAVIS_OS_NAME = osx ]; then
      cmake .. -G Xcode
      xcodebuild
    fi